TaskPlanner/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaskPlanner.Data;
using TaskPlanner.Models;

namespace TaskPlanner.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly DatabaseContext _context;

        public EmployeeController(DatabaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            var employees = await _context.Employees.ToListAsync(); 
            return View(employees);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Employees.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(employee);
        }

        public async Task<IActionResult> Edit(int?id)
        {
            if (id == null || id <= 0)
                return BadRequest();

                var employeeInDb = await _context.Employees.FirstOrDefaultAsync(e => e.Id == id);

            if (employeeInDb == null)
                return NotFound();

            return View(employeeInDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(Employee employee)
        {
            if (!ModelState.IsValid)
                return View(employee);

            _context.Entry(employee).State = EntityState.Modified;
            _context.Employees.Update(employee);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id <= 0)
                return BadRequest();

            var employeeInDb = await _context.Employees.FirstOrDefaultAsync(e => e.Id == id);

            if (employeeInDb == null)
                return NotFound();

            _context.Employees.Remove(employeeInDb);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

TaskPlanner/Controllers/ShiftController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using TaskPlanner.Data;
using TaskPlanner.Helpers;
using TaskPlanner.Models;

namespace TaskPlanner.Controllers
{
    public class ShiftController : Controller
    {

        private readonly DatabaseContext _context;

        public ShiftController(DatabaseContext context)
        {
            _context = context;
        }

        
        public async Task<IActionResult> Index()
        {
            var shifts = await _context.Shifts.ToListAsync();
            return View(shifts);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(Shift shift)
        {
            if (ModelState.IsValid)
            {
                _context.Shifts.Add(shift);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(shift);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id <= 0)
                return BadRequest();

            var shiftInDb = await _context.Shifts.FirstOrDefaultAsync(e => e.Id == id);

            if (shiftInDb == null)
                return NotFound();

            return View(shiftInDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Shift shift)
        {
            if (!ModelState.IsValid)
                return View(shift);

            _context.Shifts.Update(shift);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id <= 0)
                return BadRequest();

            var shiftInDb = await _context.Shifts.FirstOrDefaultAsync(e => e.Id == id);

            if (shiftInDb == null)
                return NotFound();

            _context.Shifts.Remove(shiftInDb);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        
        public async Task<IActionResult> EditTasks(int? id)
        {
            if (id == null || id <= 0)
                return BadRequest();

            var shiftTaskInDb = await _context.Shifts.FirstOrDefaultAsync(e => e.Id == id);

            if (shiftTaskInDb == null)
                return NotFound();

            return View(shiftTaskInDb);
        }

        public async Task<IActionResult> AddShiftTasks(int? id)
        {
            if (id == null || id <= 0)
                return BadRequest();

            var shiftInDb = await _context.Shifts.FirstOrDefaultAsync(e => e.Id == id);

            if (shiftInDb == null)
                return NotFound();

            return View(shiftInDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddShiftTasks(Shift shift)
        {
            if (!ModelState.IsValid)
                return View(shift);

            _context.Shifts.Update(shift);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult ShiftTaskAddition(int? id)
        {
            if (id == null || id <= 0)
                return BadRequest();

            var shiftInDb =  _context.Shifts.FirstOrDefaultAsync(e => e.Id == id);

            if (shiftInDb == null)
                return NotFound();

            return View(shiftInDb);
        }

        [HttpPost]
        public IActionResult ShiftTaskAddition()
        {
            int shiftId = Convert.ToInt32(HttpContext.Request.Form["shiftId"]);     
            string taskIds = HttpContext.Request.Form["taskIds"].ToString();

            TaskPlanner.Helpers.DbQueries.addTasksToShift(shiftId, taskIds);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> ViewShiftTask(int? id)
        {
           
            return View();
        }
    }
}

TaskPlanner/Controllers/WorkTaskController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaskPlanner.Data;
using TaskPlanner.Models;

namespace TaskPlanner.Controllers
{
    public class WorkTaskController : Controller
    {
        private readonly DatabaseContext _context;

        public WorkTaskController(DatabaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            var tasks = await _context.Tasks.ToListAsync();
            return View(tasks);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(WorkTask task)
        {
            if (ModelState.IsValid)
            {
                _context.Tasks.Add(task);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(task);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id <= 0)
                return BadRequest();

            var taskInDb = await _context.Tasks.FirstOrDefaultAsync(e => e.Id == id);

            if (taskInDb == null)
                return NotFound();

            return View(taskInDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(WorkTask task)
        {
            if (!ModelState.IsValid)
                return View(task);

            _context.Tasks.Update(task);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id <= 0)
                return BadRequest();

            var taskInDb = await _context.Tasks.FirstOrDefaultAsync(e => e.Id == id);

            if (taskInDb == null)
                return NotFound();

            _context.Tasks.Remove(taskInDb);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

TaskPlanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Task Planner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task Planner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shift" asp-action="Index">Vagter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Medarbejdere</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WorkTask" asp-action="Index">Opgaver</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TaskPlanner -
            <a asp-area="" asp-controller="Employee" asp-action="Index">Medarbejdere</a> |
            <a asp-area="" asp-controller="WorkTask" asp-action="Index">Arbejdsopgaver</a> |
            <a asp-area="" asp-controller="Shift" asp-action="Index">Vagter</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>